### ISSUE TITLE
Keyauth error

### ISSUE THREAD

**Issue by 123nishant** [vinclv/data-engineering-minds-kafka#2]
HI , 
Your videos are really good. 
Thanks for them. 

For the SASL authentication, I am repeatedly getting a No Keyauth error while starting the broker on my windows laptop. 

I have been searching for few days and I could not get any where . 
Really need some suggestion. 

org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /config/users/broker-admin
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:120)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at kafka.zookeeper.AsyncResponse.resultException(ZooKeeperClient.scala:576)
        at kafka.zk.KafkaZkClient.getEntityConfigs(KafkaZkClient.scala:339)

**Comment by vinclv** [comment]
Check my "Pinned Comment" in Part-5 SASL video.  This could help u.

**Comment by 123nishant** [comment]
I did that already . 
But that still does not work

**Comment by 123nishant** [comment]
C:\Kafka_1>.\bin\windows\kafka-configs.bat --zookeeper localhost:2182 --zk-tls-config-file .\config\zookeeper-client.properties --entity-type users --entity-name broker-admin --alter --add-config SCRAM-SHA-512=[password=jan1234]
Warning: --zookeeper is deprecated and will be removed in a future version of Kafka.
Use --bootstrap-server instead to specify a broker to connect to.
Completed updating config for entity: user-principal 'broker-admin'.

![image](https://user-images.githubusercontent.com/8594023/132827727-f6e16920-211e-43d8-b784-d70485498bed.png)

**Comment by 123nishant** [comment]
Please do let me know if I can give any other details. 

I am confused for few days what can be done over here.

**Comment by vinclv** [comment]
Do u face the issuer while creating topic or kafka startup or something else? bcos I see this issue related to ZK which is possible when u try to create topics or something else via zookeeper. But, nothing should be done via zookeeper anymore (As mentioned in the pinned comment)

**Comment by 123nishant** [comment]
I face this issue while starting the Kafka broker
Quite frankly I haven't gone past that.

**Comment by ghost** [comment]
Hi have the sa.e exact issue ,  and also iam using linux

**Comment by n27051538** [comment]
Add to zookeeper.properties new parameter  

    skipACL=yes

This helped to me. ACL check will be completely skipped by zookeeper, but it will check the valid SSL certificate.
